# Generated by Django 3.2.9 on 2021-12-07 18:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.DateField(default=datetime.datetime(2021, 12, 7, 18, 22, 17, 319267, tzinfo=utc))),
                ('end_time', models.DateField(default=datetime.datetime(2021, 12, 7, 18, 22, 17, 319283, tzinfo=utc))),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('birthday', models.DateField(default=datetime.datetime(2021, 12, 7, 18, 22, 17, 318462, tzinfo=utc))),
                ('email', models.CharField(max_length=50)),
                ('followed_courses', models.ManyToManyField(to='learning.Course')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.datetime(2021, 12, 7, 18, 22, 17, 319564, tzinfo=utc))),
                ('related_course', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.course')),
            ],
            options={
                'verbose_name': 'Lecture',
                'verbose_name_plural': 'Lectures',
            },
        ),
    ]
