# Generated by Django 3.2.9 on 2021-12-07 18:22

from django.db import migrations

def add_data(apps, schema_editor):
    app_name = 'learning'
    courses = ['python', 'java', 'general', 'devops', 'testing']
    lectures = ['first', 'second', 'third']
    courses_obj = []

    for course in courses:
        course_model = apps.get_model(app_name, 'Course')
        course_obj = course_model.objects.create(name=course)
        courses_obj.append(course_obj)
        for lecture in lectures:
            lect_model = apps.get_model(app_name, 'Lecture')
            lect_obj = lect_model.objects.create(name=f'{course} {lecture}', related_course=course_obj)


    for i in range(10):
        stdnt_model = apps.get_model(app_name, 'Student')
        stdnt_obj = stdnt_model.objects.create(
            first_name=str(i),
            last_name=str(i),
            patronymic=str(i),
            email=str(i)
        )
        stdnt_obj.followed_courses.add(courses_obj[i % len(courses_obj)])


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_data)
    ]